name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  image_picker: ^1.1.2 # Add image_picker dependency for selecting images
  firebase_storage: ^12.1.0
  reactive_forms: ^17.0.1
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/